test:
  #  hostport: httpbin.org:80
  #  hostport: localhost:5000
  #  uri: http://${test.hostport}
  uri: lb://httpbin


spring:
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: http://localhost:8088/api/hello
          predicates:
            - Weight=group1,2
        - id: hello_route2
          uri: http://localhost:8089/api/hello
          predicates:
            - Weight=group1,7
        - id: hello_route3
          uri: http://localhost:8089/api/hello
          predicates:
            - Weight=group1,1
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
